const JWT_SECRET = '4854vsnvut4589uy7gw45yhwgfwuvsjkt4';
const ERROR_INVALID_DATA = 400;
const ERROR_NOT_FOUND = 404;
const ERROR_DEFAULT = 500;
const STATUS_OK = 200;
const ERROR_NOT_UNIQUE = 409;
const ERROR_AUTH = 401;
const ERROR_ACCESS = 403;
const ERROR_CODE_UNIQUE = 11000;

module.exports = {
  JWT_SECRET,
  ERROR_INVALID_DATA,
  ERROR_NOT_FOUND,
  ERROR_DEFAULT,
  STATUS_OK,
  ERROR_NOT_UNIQUE,
  ERROR_AUTH,
  ERROR_ACCESS,
  ERROR_CODE_UNIQUE,
};
